MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 5
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  GEO_ATTR_ON: True
  ROI_GEO_ATTR_HEAD:
    SHARE_BOX_FEATURE_EXTRACTOR: False
    ORI_BIN: 2
    CLASS_NAME_MAP: ('Cyclist', 'Van', 'Tram', 'Car', 'Pedestrian', 'Truck')
    AVG_DIMS: ((1.73532436,  0.58028152,  1.77413709), ( 2.18928571,  1.90979592,  5.07087755), 
                (3.56092896,   2.39601093,  18.34125683), (1.52159147,  1.64443089,  3.85813679),
                (1.75554637,  0.66860882,  0.87623049), (3.07392252,   2.63079903,  11.2190799))

DATASETS:
  TRAIN: ("kitti_train", )
  #TEST: ("kitti_test",)
  TEST: ("kitti_train",)

INPUT:
  MIN_SIZE_TRAIN: (384,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 384
  MAX_SIZE_TEST: 1280
  
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"

OUTPUT_DIR: "output"

